# =============================================================================
# YASB (Yet Another Status Bar) - Configuration
# =============================================================================

# Development settings
watch_stylesheet: true
watch_config: true

# =============================================================================
# KOMOREBI INTEGRATION
# =============================================================================
# Window manager integration settings
# Remove this section if you don't use komorebi
komorebi:
  start_command: "komorebic start --whkd"
  stop_command: "komorebic stop --whkd"
  reload_command: "komorebic reload-configuration"

# =============================================================================
# BAR CONFIGURATION
# =============================================================================
bars:
  status-bar:
    enabled: true
    screens: ["*"]
    class_name: "yasb-bar"

    # Bar positioning
    alignment:
      position: "top"
      center: false

    # Visual effects
    blur_effect:
      enabled: true
      acrylic: false
      dark_mode: true
      round_corners: true
      border_color: None

    # Window behavior
    window_flags:
      always_on_top: false
      windows_app_bar: true

    # Bar dimensions
    dimensions:
      width: "100%"
      height: 36

    # Bar spacing
    padding:
      top: 5
      left: 8
      bottom: 0
      right: 8

    # Widget layout
    widgets:
      left: ["home", "komorebi_workspaces", "active_window"]
      center: ["clock", "weather"]
      right:
        [
          "whkd",
          "media",
          "traffic",
          "cpu",
          "nvidia_temp",
          "memory",
          "volume",
          "battery",
          "wifi",
          "power_menu",
        ]

# =============================================================================
# WIDGET CONFIGURATIONS
# =============================================================================

widgets:
  # ---------------------------------------------------------------------------
  # NAVIGATION & SYSTEM WIDGETS
  # ---------------------------------------------------------------------------

  home:
    type: "yasb.home.HomeWidget"
    options:
      label: "<span>\ue8e5</span>"
      menu_list:
        - { title: "Dossier Utilisateur", path: "~" }
        - { title: "Téléchargements", path: "~\\Downloads" }
        - { title: "Documents", path: "~\\Documents" }
        - { title: "Images", path: "~\\Pictures" }
      system_menu: true
      power_menu: true
      blur: true
      round_corners: true
      round_corners_type: "normal"
      border_color: "System"
      offset_top: 6
      offset_left: 0
      container_padding:
        top: 0
        left: 0
        bottom: 0
        right: 0
      alignment: "left"
      direction: "down"
      menu_labels:
        shutdown: "Éteindre"
        restart: "Redémarer"
        logout: "Se déconnecter"
        lock: "Verouiller"
        sleep: "Veille"
        system: "System Settings"
        about: "À propos"
        task_manager: "Gestionnaire des Tâches"

  active_window:
    type: "yasb.active_window.ActiveWindowWidget"
    options:
      label: "{win[title]}"
      label_alt: "[class_name='{win[class_name]}' exe='{win[process][name]}' hwnd={win[hwnd]}]"
      label_no_window: ""
      label_icon: true
      label_icon_size: 16
      max_length: 56
      max_length_ellipsis: "..."
      monitor_exclusive: true

  # ---------------------------------------------------------------------------
  # WORKSPACE MANAGEMENT (KOMOREBI)
  # ---------------------------------------------------------------------------

  komorebi_workspaces:
    type: "komorebi.workspaces.WorkspaceWidget"
    options:
      label_offline: "Komorebi Offline"
      label_workspace_btn: "\ueabc"
      label_workspace_active_btn: "\uebb4"
      label_workspace_populated_btn: "\uea71"
      label_zero_index: false
      hide_empty_workspaces: false
      hide_if_offline: true

  komorebi_active_layout:
    type: "komorebi.active_layout.ActiveLayoutWidget"
    options:
      hide_if_offline: true
      label: "{icon}"
      layouts:
        [
          "bsp",
          "columns",
          "rows",
          "grid",
          "vertical_stack",
          "horizontal_stack",
          "ultrawide_vertical_stack",
          "right_main_vertical_stack",
        ]
      layout_icons:
        bsp: "BSP"
        columns: "COLS"
        rows: "ROWS"
        grid: "GRID"
        vertical_stack: "V-STACK"
        horizontal_stack: "H-STACK"
        ultrawide_vertical_stack: "W-STACK"
        right_main_vertical_stack: "RMV-STACK"
        monocle: "MONOCLE"
        maximised: "MAX"
        floating: "FLOATING"
        paused: "PAUSED"
      callbacks:
        on_left: "next_layout"
        on_middle: "toggle_monocle"
        on_right: "prev_layout"

  # ---------------------------------------------------------------------------
  # DATE & TIME WIDGETS
  # ---------------------------------------------------------------------------

  clock:
    type: "yasb.clock.ClockWidget"
    options:
      label: "{%a %d, %b %H:%M}"
      label_alt: "{%A %d %B %Y, %H:%M}"
      locale: "fr_FR" # Language for date formatting
      timezones: [] # Looking up time zone info from registry
      # timezones: ["America/Montreal"] # Custom timezone example

  # ---------------------------------------------------------------------------
  # WEATHER INFORMATION
  # ---------------------------------------------------------------------------

  weather:
    type: "yasb.weather.WeatherWidget"
    options:
      label: "<span>{icon}</span> {temp}"
      label_alt: "{location}: Min {min_temp}, Max {max_temp}, Humidité {humidity}"
      api_key: "3bf4cf9a7c3f40d6b31174128242807" # Get your free API key from https://www.weatherapi.com/
      update_interval: 1000 # Update interval in seconds, Min 600 seconds
      hide_decimal: true
      location: "Paris, France" # Format: "COUNTRY CITY ZIP_CODE" or just city
      callbacks:
        on_left: "toggle_label"
        on_right: "toggle_card"
      icons:
        sunnyDay: "\ue30d"
        clearNight: "\ue32b"
        cloudyDay: "\udb81\udd99"
        cloudyNight: "\ue311"
        rainyDay: "\udb81\ude7e"
        rainyNight: "\udb81\ude7e"
        snowyIcyDay: "\udb81\udd98"
        snowyIcyNight: "\udb81\udd98"
        blizzardDay: "\uebaa"
        default: "\uebaa"
        # Available variables: {temp}, {min_temp}, {max_temp}, {temp_f}, {min_temp_f}, {max_temp_f}, {location}, {humidity}, {icon}, {conditions}

  # ---------------------------------------------------------------------------
  # SYSTEM MONITORING WIDGETS
  # ---------------------------------------------------------------------------

  cpu:
    type: "yasb.cpu.CpuWidget"
    options:
      label: "<span>\uf4bc</span> {info[percent][total]}%"
      label_alt: "<span>\uf437</span> {info[histograms][cpu_percent]}"
      update_interval: 2000
      histogram_icons:
        - '\u2581' # 0%
        - '\u2581' # 10%
        - '\u2582' # 20%
        - '\u2583' # 30%
        - '\u2584' # 40%
        - '\u2585' # 50%
        - '\u2586' # 60%
        - '\u2587' # 70%
        - '\u2588' # 80%+
      histogram_num_columns: 8
      callbacks:
        on_right: "exec cmd /c Taskmgr"

  memory:
    type: "yasb.memory.MemoryWidget"
    options:
      label: "<span>\uf4bc</span> {virtual_mem_free}"
      label_alt: "<span>\uf4bc</span> {virtual_mem_percent}%"
      update_interval: 10000
      callbacks:
        on_right: "exec cmd /c Taskmgr"

  nvidia_temp:
    type: "yasb.custom.CustomWidget"
    options:
      label: "<span class=\"gpu-icon\">\udb83\udfb2</span>{data}°C"
      label_alt: "{data}"
      class_name: "system-widget"
      exec_options:
        run_cmd: "powershell nvidia-smi --query-gpu=temperature.gpu --format=csv,noheader"
        run_interval: 10000 # Update every 10 seconds
        return_format: "string"

  battery:
    type: "yasb.battery.BatteryWidget"
    options:
      label: "<span>{icon}</span>{percent}%"
      label_alt: "{icon} {percent}% | time: {time_remaining}"
      charging_options:
        icon_format: "{charging_icon}"

  # ---------------------------------------------------------------------------
  # NETWORK & CONNECTIVITY
  # ---------------------------------------------------------------------------

  wifi:
    type: "yasb.wifi.WifiWidget"
    options:
      label: "<span>{wifi_icon}</span>"
      label_alt: "{wifi_name} {wifi_strength}%"
      update_interval: 5000
      callbacks:
        on_left: "exec cmd.exe /c start ms-settings:network"
        on_middle: "do_nothing"
        on_right: "toggle_label"

  traffic:
    type: "yasb.traffic.TrafficWidget"
    options:
      label: "<span>\udb86\uddb3</span>{download_speed} | <span>\udb86\uddb2</span>{upload_speed}"
      label_alt: "Download {download_speed} \ue621 Upload {upload_speed}"
      update_interval: 2000 # Update interval should be a multiple of 1000
      speed_unit: "bytes"
      hide_decimal: true
      speed_threshold:
        min_upload: 1000
        min_download: 1000
      callbacks:
        on_left: "toggle_label"
        on_right: "toggle_menu"

  ip_info:
    type: "yasb.custom.CustomWidget"
    options:
      label: "<span>\udb81\udd9f</span> {data[ip]}"
      label_alt: "<span>\uf450</span> {data[city]} {data[region]}, {data[country]}"
      class_name: "ip-info-widget"
      exec_options:
        run_cmd: "curl.exe https://ipinfo.io"
        run_interval: 120000 # Update every 2 minutes
        return_format: "json"
      callbacks:
        on_left: "toggle_label"
        on_middle: "exec cmd /c ncpa.cpl" # Open network settings
        on_right: "exec cmd /c start https://ipinfo.io/{data[ip]} " # Open ipinfo in browser

  # ---------------------------------------------------------------------------
  # AUDIO & MEDIA WIDGETS
  # ---------------------------------------------------------------------------

  volume:
    type: "yasb.volume.VolumeWidget"
    options:
      label: "<span>{icon}</span> {level}"
      label_alt: "{volume}"
      volume_icons:
        - "\ueee8" # Icon for muted
        - "\uf026" # Icon for 0-10% volume
        - "\uf027" # Icon for 11-30% volume
        - "\uf027" # Icon for 31-60% volume
        - "\uf028" # Icon for 61-100% volume
      callbacks:
        on_right: "exec cmd.exe /c start sndvol"

  media:
    type: "yasb.media.MediaWidget"
    options:
      label: "{title}"
      label_alt: "{title} - {artist}"
      max_field_size:
        label: 20
        label_alt: 30
      show_thumbnail: true
      controls_only: false
      controls_left: true
      hide_empty: true
      thumbnail_alpha: 80
      thumbnail_padding: 8
      thumbnail_corner_radius: 16 # Set to 0 for square corners
      icons:
        prev_track: "\ue892"
        next_track: "\ue893"
        play: "\ue768"
        pause: "\ue769"

  # ---------------------------------------------------------------------------
  # POWER & SESSION MANAGEMENT
  # ---------------------------------------------------------------------------

  power_menu:
    type: "yasb.power_menu.PowerMenuWidget"
    options:
      label: "\uf011"
      uptime: True
      blur: False
      blur_background: True
      animation_duration: 300 # Milliseconds
      button_row: 3 # Number of buttons per row (min 1, max 5)
      buttons:
        lock: ["\uea75", "Verouiller"]
        signout: ["\udb80\udf43", "Se déconnecter"]
        sleep: ["\u23fe", "Veille"]
        shutdown: ["\uf011", "Éteindre"]
        restart: ["\uead2", "Redémarer"]
        hibernate: ["\uf28e", "Veille Prolongé"]
        cancel: ["\udb81\udf3a", "Annuler"]
        # force_shutdown: ["\uf011","Force Shut Down"]
        # force_restart: ["\uead2","Force Restart"]

  # ---------------------------------------------------------------------------
  # LANGUAGE & LOCALIZATION
  # ---------------------------------------------------------------------------

  lang:
    type: "yasb.custom.CustomWidget"
    options:
      label: "<span>\uf1ab</span>{data}"
      label_alt: "{data}"
      class_name: "lang-widget"
      exec_options:
        run_cmd: "powershell Add-Type -AssemblyName System.Windows.Forms;([System.Windows.Forms.InputLanguage]::CurrentInputLanguage).Culture.Name"
        run_interval: 10000 # Update every 10 seconds
        return_format: "string"

  # ---------------------------------------------------------------------------
  # APPLICATION SHORTCUTS
  # ---------------------------------------------------------------------------

  apps:
    type: "yasb.applications.ApplicationsWidget"
    options:
      label: "{data}"
      app_list:
        # Application shortcuts (commented out - customize as needed)
        # - {icon: "\uf489", launch: "wt"}
        # - {icon: "\uf413", launch: "explorer c:\\Users\\amn"}
        # - {icon: "\udb82\ude1e", launch: "C:\\Users\\amn\\AppData\\Local\\Programs\\Microsoft VS Code\\Code.exe"}
        # - {icon: "\udb80\ude39", launch: "C:\\Program Files\\Mozilla Firefox\\firefox.exe"}
        # - {icon: "\uf1ff", launch: "C:\\Users\\amn\\AppData\\Local\\Discord\\Update.exe --processStart Discord.exe"}
        # - {icon: "\ue217", launch: "C:\\Users\\amn\\AppData\\Roaming\\Telegram Desktop\\Telegram.exe"}

        # System shortcuts
        - { icon: "\uf0a2", launch: "notification_center" }
        - { icon: "\ueb51", launch: "quick_settings" }
        - { icon: "\uf422", launch: "search" }
        # - {icon: "\uf46a", launch: "cmd.exe /c start ms-settings:windowsupdate"}
        # - {icon: "\udb84\udf55", launch: "widget"}
        # Available shortcuts: quick_settings, notification_center, search, widget, launcher (launcher triggers ALT+A)

  win_button:
    type: "yasb.custom.CustomWidget"
    options:
      label: "\ue62a"
      label_alt: "\ue62a"
      class_name: "system-widget"
      callbacks:
        on_left: "exec start_menu"

  # ---------------------------------------------------------------------------
  # DEVELOPMENT & INTEGRATION WIDGETS
  # ---------------------------------------------------------------------------

  whkd:
    type: "yasb.whkd.WhkdWidget"
    options:
      label: "<span>\uf11c</span>"
      special_keys:
        - key: "win"
          key_replace: "\ue70f"
        - key: "ctrl"
          key_replace: "Ctrl"
        - key: "alt"
          key_replace: "Alt"
        - key: "shift"
          key_replace: "Shift"
        - key: "left"
          key_replace: "\u2190"
        - key: "right"
          key_replace: "\u2192"
        - key: "up"
          key_replace: "\u2191"
        - key: "down"
          key_replace: "\u2193"

  github:
    type: "yasb.github.GithubWidget"
    options:
      label: "<span>\ueba1</span>"
      label_alt: "Notifications {data}" # {data} returns number of unread notifications
      token: ghp_xxxxxxxxxxx # GitHub Personal access tokens (classic) - https://github.com/settings/tokens
      max_notification: 20 # Max notifications in menu (max: 50)
      only_unread: false # Show only unread or all notifications
      max_field_size: 54 # Max title characters before truncation
      update_interval: 300 # Check for notifications every 5 minutes

  # ---------------------------------------------------------------------------
  # CUSTOMIZATION WIDGETS
  # ---------------------------------------------------------------------------

  wallapers:
    type: "yasb.wallpapers.WallpapersWidget"
    options:
      label: "<span>\udb83\ude09</span>"
      image_path: "C:\\Users\\xxx\\Images" # Path to wallpaper folder
      change_automatically: false # Auto-change wallpaper
      update_interval: 60 # Auto-change interval in seconds
